### ISSUE TITLE
Binaries/Compilation instructions for the simpleminded?

### ISSUE THREAD

**Issue by fpqc** [ionescu007/lxss#3]
Any chance you could give those of us who don't use Visual Studio a little readme on how to build, or maybe put up precompiled binaries?  Thanks!

**Comment by fpqc** [comment]
Okay, I got lxlaunch to compile, but it seems like it needs elevation to run, and when I run 
`lxlaunch.exe /bin/bash` it just outputs some garbage characters, says root@fpqc-pc something something then instantly exits.

**Comment by ashkalra-bst** [comment]
I am getting a similar output when i run lxlaunch.exe (without any arguments too), outputs some garbage characters and then instantly exits.

**Comment by ashkalra-bst** [comment]
Actually, lxlaunch works fine on my test Win10 machine when i run it as Admin.

**Comment by ionescu007** [comment]
Hi,

@fpqc: If you don't use visual studio, just running gcc on the .cpp files with standard compiler settings should work fine. Looks like you got it working, so if you needed to do anything special, do you want to submit a pull request for the README.MD with your instructions?

@fpqc: Yes, I haven't implemented full console support -- this was more of a PoC. Launching complex things like /bin/bash would require creating the named pipes for STDIN and then having a thread to handle the input. Additionally, the "garbage" characters are because the console needs to be set to VT-100 (AFAIK) mode, which I don't do. lxlaunch.exe was mainly implemented to show how to launch simple ELF binaries, not full-fledged console I/O. For example, try it on a man page -- it should render fine.

@ashkalra-bst If you don't run it as admin, you see "garbage characters"? Can you run it from cmd.exe and post a screenshot? Thanks.

**Comment by fpqc** [comment]
@ionescu007 It was enough to install VS community 2015 (necessary) and the VS 15 beta 3 (sufficient but perhaps unnecessary, not sure) , and the IDE for 2015 says which deps you need to install (Win 8.1 sdk and vc++ runtime, iirc).  I installed VS15 beta first bc it comes with the Win10 SDK but I am not sure it is needed.

Question: Do you think using vxserver/vxclient, you can run cmd and powershell in a WSL/LXSS terminal emulator (we already have these working for months over on the WSL github using vcXsrv).

Also, can lxlaunch in theory (if you named the pipes and set what you said) start an X terminal emulator in interactive mode without doing bash.exe -c "DISPLAY:0 <term emulator>"

Also, we really want to see your blackhat talk.  Any idea when it will be youtubeable?

**Comment by ionescu007** [comment]
@fpqc Oh, I thought you used raw GCC after all. Looks like you used VS, so that's fine :) lxlaunch in theory can perfectly start an X terminal emulator, yes, without using bash.exe -c. But there's a little more work to implement the pipes there. I may whip up a quick PoC at some point. The BH talk should be on Youtube in a few months, that's what BH did last year. Obviously you have the slides here. As for running cmd inside of LX, I don't believe console/pipe marshaling works from LX to NT unfortunately. Obviously you can fake it with sockets.

**Comment by fpqc** [comment]
Yeah, @xilun has got cmd and powershell working in script execution mode using a hack called outbash or cbwin (basically attaching a port and tcp server to each cmd window) (cbwin I think is short for "call-back to windows"), and it kind of works (very laggy though) in interactive mode.  

Maybe using the new COM interfaces you've shown, he can change the way it works from using TCP to using the zero-copy IPC you have demonstrated (perhaps with a speed improvement).

**Comment by xilun** [comment]
Sorry for hijacking this thread a bit, but as I was cited... :)

@fpqc I will probably not use interfaces not documented by MS (I use NtSuspend / NtResume because there are no Win32 equivalent, but they are highly unlikely to change -- WSL internals will probably change?), even if it is highly interesting to have that info available, so thank you @ionescu007 for this work! (and for the Windows Internals book, and so over :)

The main problems cbwin have right now are unrelated to how IPC is performed; how to pass the command line in the most useful fashion for the user (escaping/quoting/translating or not the params), and how the Windows console behave when used both by Win32 and WSL programs.

Of course using TCP might not be the most elegant solution, and it does have some drawbacks (each identification of a caller process has a very high cost), but it also have neat advantages, especially since WSL syscalls are not perfect yet (and so with TCP I can check the behavior of the caller on a linux kernel when needed).

> it kind of works (very laggy though) in interactive mode

I'm interested in details about the laggy part. @fpqc don't hesitate to open a cbwin issue if needed.

**Comment by fpqc** [comment]
@xilun I last tested interactive mode in 0.6 when you said it wasn't ready.

**Comment by ashkalra-bst** [comment]
Hello Alex,

I tried re-executing lxlaunch and it works fine without the elevated/admin rights, sorry about that.

I have another question, in your slides you mention that the LXCORE's internal syscall handlers are protected by PatchGuard, is there a way to extend the functionality of say Linux's open() syscall by hooking the specific syscall handler and provide the extended functionality via a kernel mode driver ?

Thanks.

**Comment by ionescu007** [comment]
Hi @ashkalra-bst: No, hooking LXPSYSCALL_Open will result in a PatchGuard violation.

**Comment by fpqc** [comment]
@ionescu007 Is lxclient already obsolete, by the way?  It seems like lxext and lxexec extend its functionality.

Also, I wonder if lxserver could be expanded in scope to behave like a sort of Windows Console TTY manager (sort of like how rxvtd works in Linux).  For example, one could add an option to lxexec called say, `-f` for `--console-forwarding`, so if you did, say, `lxexec -f cmd` or `lxexec -f powershell`, instead of opening an interactive console in Windows, lxserver takes the output of cmd to the console and forwards it to the lxexec display (instead of opening separate sockets for each instance, you could maybe tag each console process with the PID of the lxexec process that generated it, then somehow tag the forwarded messages from a console launched from lxexec with PID n be tagged n?).

Reason why this might be interesting is you could do cool things like run CMD and powershell in tmux, use a nice X VTE with them.  

Going to read up on Windows console documentation.

**Comment by ionescu007** [comment]
@fpqc: The connection is two-way. And either end can be a server or a client. You just have to define a protocol and who does the read/write. For example, with the token donation mode, the other side sends (Win32) and the Lx side receives.

And yes, lxext avoids needing to have a binary run as root on the LX Side, as long you do the ld preload trick (which requires root only once). And additionally, because the code now runs in the init process (PID 1), it's allowed access to /dev/lxss without the special registry key.

The Win32 side still needs to be run as Admin however, and yes, when it 'launches' things, it will unfortunately run them as admin. The correct fix is to actually call CreateProcessAsUser and get the instance token in some way.

Just to point out, this work is done as PoC. RS2 will have an actually official way to launch Win32 apps from Lx :)

**Comment by ionescu007** [comment]
@fpqc The latest version now implements VT-100 and UTF-8 correctly. I no longer see garbage characters.

**Comment by fpqc** [comment]
Thanks! Will try later =]

**Comment by ionescu007** [comment]
@ashkalra-bst @fpqc Version 1.2.0 now handles input/output from Linux processes correctly. The process no longer instantly exits.
